# Generated by Django 3.1.2 on 2020-10-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201022_1839'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='director',
            unique_together={('name', 'surname')},
        ),
    ]
